---
- name: Download Boot2Docker
  get_url: >
    url=https://github.com/boot2docker/osx-installer/releases/download/v1.3.2/Boot2Docker-1.3.2.pkg
    dest={{ downloads_directory }}/Boot2Docker-1.3.2.pkg

- name: Install Boot2Docker
  command: >
    installer -package {{ downloads_directory }}/Boot2Docker-1.3.2.pkg -target /
    creates=/Applications/boot2docker.app
  sudo: yes
