---
- name: Download MacVim
  get_url: >
    url=https://github.com/macvim-dev/macvim/releases/download/snapshot-107/MacVim.dmg
    dest={{ downloads_directory }}/MacVim-snapshot-107.dmg

- name: Mount MacVim image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach MacVim-snapshot-107.dmg
    creates=/Volumes/MacVim

- name: Install MacVim
  command: >
    cp -r /Volumes/MacVim/MacVim.app /Applications
  become: yes

- name: Install console binary
  command: >
    cp /Volumes/MacVim/mvim /usr/local/bin
  become: yes

- name: Unmount MacVim image
  command: hdiutil detach /Volumes/MacVim
