---
- hosts: 0.0.0.0
  connection: local
  vars:
    home_directory: /Users/{{ ansible_user_id }}
    downloads_directory: /{{ home_directory }}/.ansible/downloads
  roles:
    - ansible-download-directory
    - ssh-directory
    - caps-lock-remapped-to-control
    - iterm
    - known-hosts
    - dropbox
    - dropbox-ssh-key
    - jre
    - jdk
    - skype
    - ynab
    - steam
    - theremin
    - licecap
    - mac-ports
    - xquartz
    - chef
    - r
    - lua
    - luajit
    - python3
    - skitch
    - vlc
    - light-table
    - octave
    - haskell
    - ghc-mod
    - hoogle
    - hdevtools
    - hlint
    - hindent
    - pointfree
    - purescript
    - silverlight
    - hangouts
    - google-chrome
    - firefox
    - firefox-pentadactyl
    - boot2docker
    - vagrant
    - vagrant-vbguest
    - bundler
    - tmuxinator
    - heroku
    - zsh
    - homebrew
    - git
    - node
    - powerline
    - oh-my-zsh
    - hadoop
    - terminal-notifier
    - reattach-to-user-namespace
    - fontforge
    - monaco-for-powerline
    - irssi
    - leiningen
    - jmeter
    - mplayer
    - mpd
    - mpc
    - mpdscribble
    - vimpc
    - tree
    - wget
    - htop
    - p7zip
    - tree
    - tmux
    - ctags
    - the-silver-searcher
    - vault
    - jshint
    - pulp
    - dotfiles
    - vimfiles
