---
- name: Download Vagrant
  get_url: >
    url=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1.dmg
    dest={{ downloads_directory }}/vagrant_1.8.1.dmg

- name: Mount Vagrant image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach vagrant_1.8.1.dmg
    creates=/Volumes/Vagrant

- name: Install Vagrant
  command: >
    installer -package /Volumes/Vagrant/Vagrant.pkg -target /
  sudo: yes

- name: Unmount Vagrant image
  command: hdiutil detach /Volumes/Vagrant
