---
- name: Ensure the mpd directories exist
  file: path=/Users/{{ ansible_user_id }}/{{ item }} state=directory
  with_items:
    - .mpd
    - .mpd/playlists

- name: Check out the dotfiles GitHub repository
  git: >
    repo=git@github.com:mpereira/dotfiles.git
    dest=/Users/{{ ansible_user_id }}/.dotfiles

- name: Install dotfiles
  command: >
    chdir=/Users/{{ ansible_user_id }}/.dotfiles
    rake install
