---
- name: Download Prey
  get_url: >
    url=https://s3.amazonaws.com/prey-releases/node-client/1.3.8/prey-mac-1.3.8-x64.pkg
    dest={{ downloads_directory }}/prey-mac-1.3.8-x64.pkg

- name: Install Prey
  shell: >
    API_KEY=foobar123 installer -package {{ downloads_directory }}/prey-mac-1.3.8-x64.pkg -target /
  sudo: yes
