---
- name: Download ffmpeg
  get_url: >
    url=http://www.ffmpegmac.net/resources/SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_30.08.2016.zip
    dest={{ downloads_directory }}/SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_30.08.2016.zip

- name: Extract ffmpeg archive
  command: >
    chdir={{ downloads_directory }}
    unzip -u SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_30.08.2016.zip -d SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_30.08.2016

- name: Install ffmpeg binaries
  shell: >
    cp {{ downloads_directory }}/SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_30.08.2016/* /usr/local/bin
  become: true
