---
- name: Download Skitch
  get_url: >
    url=http://cdn1.evernote.com/skitch/mac/release/Skitch-2.7.1.zip
    dest={{ downloads_directory }}/Skitch-2.7.1.zip

- name: Extract Skitch zip archive
  command: >
    chdir={{ downloads_directory }}
    unzip Skitch-2.7.1.zip -d Skitch-2.7.1/
    creates=Skitch-2.7.1/

- name: Copy Skitch.app to Applications directory
  command: >
    cp -R {{ downloads_directory }}/Skitch-2.7.1//Skitch.app /Applications
    creates=/Applications/Skitch.app
  sudo: yes
