---
- name: Download luajit
  get_url:
    url=http://luajit.org/download/LuaJIT-2.0.4.tar.gz
    dest={{ downloads_directory }}/LuaJIT-2.0.4.tar.gz

- name: Extract luajit
  unarchive:
    src={{ downloads_directory }}/LuaJIT-2.0.4.tar.gz
    dest={{ downloads_directory }}
    creates={{ downloads_directory }}/LuaJIT-2.0.4

- name: Build and install luajit
  shell: >
    chdir={{ downloads_directory }}/LuaJIT-2.0.4
    make install PREFIX=/usr
  sudo: yes
