---
- name: Download MacPorts
  get_url: >
    url=https://distfiles.macports.org/MacPorts/MacPorts-2.2.1-10.9-Mavericks.pkg
    dest={{ downloads_directory }}/MacPorts-2.2.1-10.9-Mavericks.pkg

- name: Install MacPorts
  command: >
    chdir={{ downloads_directory }}
    installer -package MacPorts-2.2.1-10.9-Mavericks.pkg -target /
    creates=/opt/local/bin/port
  sudo: yes
