---
- name: Download Neovim
  get_url:
    url=https://github.com/neovim/neovim/archive/v0.1.5.tar.gz
    dest={{ downloads_directory }}/neovim.v0.1.5.tar.gz

- name: Extract Neovim
  command: >
    tar -xjvf {{ downloads_directory }}/neovim.v0.1.5.tar.gz
    -C {{ downloads_directory }}
    creates={{ downloads_directory }}/neovim-0.1.5

- name: Install Neovim dependencies
  homebrew: name={{ item }}
  with_items:
    - libtool
    - automake
    - cmake
    - pkg-config
    - gettext

- name: Build and install Neovim
  shell: >
    chdir={{ downloads_directory }}/neovim-0.1.5
    rm -rf build
    && make clean
    && make CMAKE_BUILD_TYPE=Release
    && sudo make install
