- name: Check out powerline git repository
  git: >
    repo=https://github.com/Lokaltog/powerline.git
    dest={{ downloads_directory }}/powerline
    update=no

- name: Create "Monaco for Powerline.otf"
  command: >
    fontforge -script {{ downloads_directory }}/powerline/font/fontpatcher.py /System/Library/Fonts/Monaco.dfont
    creates=Monaco\ for\ Powerline.otf

- name: Move "Monaco for Powerline.otf" to ~/Library/Fonts
  command: >
    mv Monaco\ for\ Powerline.otf {{ home_directory }}/Library/Fonts
    creates={{ home_directory }}/Library/Fonts/Monaco\ for\ Powerline.otf
